FROM alpine:3.20

ARG TARGETPLATFORM

RUN mkdir -p /home/argocd/cmp-server/config /home/argocd/cmp-server/plugins /tmp \
    && chown -R 999:999 /home/argocd /tmp

COPY --chown=999:999 $TARGETPLATFORM/kubenv-argocd-cmp /usr/local/bin/kubenv-argocd-cmp
COPY --chown=999:999 packaging/argocd/plugin.yaml /home/argocd/cmp-server/config/plugin.yaml

USER 999
ENTRYPOINT ["/var/run/argocd/argocd-cmp-server"]
